# 定义 stages
stages:
  - build

# 打包push
job2:
  stage: build
  script:
    - echo "build start"
    - cnpm config set registry http://registry.npm.neoclub.cn
    - cnpm config set //registry.npm.neoclub.cn/:email "admin@neoclub.cn"
    - cnpm config set //registry.npm.neoclub.cn/:username "admin"
    - cnpm config set //registry.npm.neoclub.cn/:_password "YWRtaW5AMTIzNDU2"
    - cnpm publish
    - echo "build success"
