# 定义 stages
stages:
  - build

# 打包push
job2:
  stage: build
  script:
    - echo "build start"
    - spawn cnpm login

    - expect "Username:"
    - send "admin"

    - expect "Password:"
    - send "admin@123456"

    - expect "Email:"
    - send "admin@neoclub.cn"

    - echo "build success"
