# 定义 stages
stages:
  - build

# 打包push
job2:
  stage: build
  script:
    - echo "build start"
    - cnpm login

    - "admin"

    - "admin@123456"

    - "admin@neoclub.cn"

    - echo "build success"
